### PR TITLE
Unify home screen

### PR DESCRIPTION
**Pull request by sdunster**
* This is the first step towards building a notifications-like screen.
* Idea here is to automatically show things that are relevant to the user such as:
  * Ongoing events
  * New schedule requests (request for assistance with specified time frame)
  * Ongoing schedule update request (user is nearing the end of the availability they have filled out)
* As these items are actioned (ie schedule is updated or an event is closed) the items drop out of this list. You could still access a schedule or event from the appropriate tab if you need to get back to it.

### CODE REVIEW

**Comment by sdunster** [comment]
screen shot 2018-02-14 at 16 21 58

**Comment by sjmcculloch** [comment]
You can add spacing to the first item using:

```<Holder margin>
<MyComponent>
</Holder>
```

**Comment by sdunster** [comment]
I decided to leave the margin thing un-addressed. I have a better fix incoming.

**Comment by sdunster** [comment]
See #217

**Pull request merged**
