### PR TITLE
optimisticResponse for createTimeSegment

### PR DESCRIPTION
**Pull request by OSPFNeighbour**
Makes the UI a little more responsive by estimating what the server will return and warming up the cache

### CODE REVIEW

**Comment by OSPFNeighbour** [comment]
The optimisticResponse data must look the same as the answer you are
optimistically expecting, so we need the id. given that we don't know it
yet it just needs to be unique in the cache so -1 is a safe bet.

Once the real data returns the cache will sort it's self out.

**Comment by OSPFNeighbour** [comment]
Further to this, if we assume all negative IDs are optimistic we can have
the UI render them differently to give the user some feedback that it's
still loading

**Comment by sdunster** [comment]
You've confirmed the data gets wiped upon refresh moments later?

**Comment by OSPFNeighbour** [comment]
Yes, the cache is managed correctly.

**Pull request merged**
