### PR TITLE
Push token registration framework

### PR DESCRIPTION
**Pull request by sdunster**
* `PushManager` to manage registration and notification event handling
* `<PushHandler>` to manage the lifecycle of push automatically as a React
  component
* Implement dummy push provider to prove it works.
* Successfully syncs dummy push tokens to the server even when there is an
  async update. Tested with multiple login, logout in one session.

### CODE REVIEW

**Comment by sjmcculloch** [comment]
lgtm - just need to resolve the app.js conflict.

**Comment by sdunster** [comment]
untuck tests using Promises™

**Comment by sdunster** [comment]
rebase

**Comment by sdunster** [comment]
Fixed some bugs
* prevent registering more than once
* race condition during registration

**Pull request merged**
