### PR TITLE
Make the more/burger menu a little bit more friendly

### PR DESCRIPTION
**Pull request by sdunster**
* `<ListItem>` now supports showing icons on the left or the right.
  * Adjusted the icon spacing, styles so that the text lines up better and
    there is more padding. This shows pretty clearly on home screen.
* Implement more menu with `<ListItem>` and add some descriptive text and
  icons.

### CODE REVIEW

**Comment by sdunster** [comment]
screen shot 2018-04-22 at 15 27 57

**Comment by sdunster** [comment]
screen shot 2018-04-22 at 15 28 14

**Comment by sdunster** [comment]
Fix lint.

**Comment by OSPFNeighbour** [comment]
Vertical center left icon?

Can you confirm if the sub text will overflow ontop of the icon?

**Comment by OSPFNeighbour** [comment]
Confirmed my self they dont overlap. nice.


Yeah, vertical align might look better

**Comment by sdunster** [comment]
rebased

**Comment by sdunster** [comment]
unfuck rebase

**Comment by sdunster** [comment]
one more attempt :/

**Comment by sdunster** [comment]
* Tweak some styles to ensure the `<ListItem>` text flexes and the icons are
  appropriately centered.

**Pull request merged**
