### PR TITLE
Major client upgrades - react-native and react-native-device-info

### PR DESCRIPTION
**Pull request by sdunster**
Update react-native: 0.50.4 -> 0.55.3
* Waste an hour manually resolving merge conflict in xcode config
* Clean up recovered files
* Remove android SDK min version from `AndroidManifest.xml` because I assume it uses the gradle config instead.
* Most of the other changes were performed as part of the `react-native-git-upgrade` script
* Change android version string to 0.1 to match iOS.
* Xcode "Run" build configuration set to debug. Build for archive (for app store, TestFlight etc) is still "Debug".

---

Upgrade react-native-device-info
* react-native-device-info: 0.17.2 -> 0.21.5
* re-shuffle some iOS project stuff

### CODE REVIEW

**Comment by OSPFNeighbour** [comment]
Navigation seems to be a little hurt from this, warnings about children when you change tabs

**Comment by sdunster** [comment]
Please share details here or in an issue - I think we should fix them separately.

**Comment by sdunster** [comment]
rebase should be no more warnings except maybe the device info one.

**Comment by OSPFNeighbour** [comment]
Do it :p

**Comment by sdunster** [comment]
unknown

**Comment by OSPFNeighbour** [comment]
Where do you find these

**Comment by sdunster** [comment]
Tests fail because the snapshots need updating with new props from react native I assume.

**Comment by sdunster** [comment]
Update snapshots. Eye-balling now.

**Comment by sdunster** [comment]
Just want to make sure I can build and run iOS and Android shells.

**Comment by sdunster** [comment]
iOS build seems funny - i couldn't get push to work. I'll investigate more tomorrow.

**Pull request merged**
